---
user_name: kamil
user_home: "/home/{{ user_name }}"

unwanted_packages:
  - mediawriter
  - gnome-tour
  - gnome-system-monitor
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-common
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-contacts
  - gnome-classic-session
  - gnome-boxes
  - showtime

base_packages:
  - firefox
  - neovim
  - tmux
  - ncdu
  - python3-psutil
  - tealdeer
  - flatpak
  - fastfetch
  - xdg-desktop-portal
  - trash-cli
  - htop
  - btop
  - wireshark

flatpak_apps:
  - org.mozilla.Thunderbird
  - md.obsidian.Obsidian
  - com.spotify.Client
  - com.slack.Slack
  - com.discordapp.Discord
  - com.bitwarden.desktop
  - com.mikrotik.WinBox
  - com.anydesk.Anydesk
  - com.calibre_ebook.calibre
  - org.chromium.Chromium
  - org.filezillaproject.Filezilla
  - com.obsproject.Studio
  - org.qbittorrent.qBittorrent
  - org.remmina.Remmina
  - org.videolan.VLC
  - org.onlyoffice.desktopeditors

wallpaper_url: "https://4kwallpapers.com/images/wallpapers/brown-mountains-aerial-view-mountain-range-landscape-3440x1440-2837.jpg"
wallpaper_path: "{{ user_home }}/.config/background"

taskbar_apps:
  - firefox.desktop
  - org.kde.konsole.desktop
  - org.kde.dolphin.desktop
  - org.mozilla.Thunderbird.desktop
  - md.obsidian.Obsidian.desktop
  - codium.desktop
  - com.mikrotik.WinBox.desktop
  - com.spotify.Client.desktop
  - com.slack.Slack.desktop
  - com.discordapp.Discord.desktop
  - steam.desktop

dotfiles:
  - src: files/bashrc
    dir: "{{ user_home }}"
    file: ".bashrc"
    dir_mode: "0700"
  - src: files/fastfetch.jsonc
    dir: "{{ user_home }}/.config/fastfetch"
    file: "config.jsonc"
    dir_mode: "0755"
  - src: files/neovim.lua
    dir: "{{ user_home }}/.config/nvim/"
    file: "init.lua"
    dir_mode: "0755"
