---
- name: Add Flathub repository (user)
  become_user: "{{ user_name }}"
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Flatpak applications
  become_user: "{{ user_name }}"
  community.general.flatpak:
    name: "{{ flatpak_apps }}"
    state: present
    method: user
