---
- name: Install base packages
  package:
    name: "{{ base_packages }}"
    state: present



- name: Ensure group "wireshark" exists
  ansible.builtin.group:
    name: wireshark
    state: present

- name: Add user to wireshark group
  user:
    name: "{{ user_name }}"
    groups: wireshark
    append: true
