---
- name: Install RPM Fusion free repository
  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present

- name: Install RPM Fusion nonfree repository
  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present

- name: Enable fedora-cisco-openh264 repository
  ansible.builtin.ini_file:
    path: /etc/yum.repos.d/fedora-cisco-openh264.repo
    section: fedora-cisco-openh264
    option: enabled
    value: "1"

- name: Refresh DNF cache
  ansible.builtin.dnf:
    update_cache: true
